name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    - name: nodecheck
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      working-directory: ./movieapp
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ./movieapp/build
